services:
  ai-dev-server:
    image: registry.correlion.ai/ai-dev-server:latest
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
        - /home/david/scripts:/scripts
        - /var/run/docker.sock:/var/run/docker.sock
        - /home/david/n8n-workflows-backup:/home/david/n8n-workflows-backup
    environment:
      - PYTHONUNBUFFERED=1
      - MCP_BEARER_TOKEN=${MCP_BEARER_TOKEN}
      - N8N_BASE_URL=${N8N_BASE_URL}
      - N8N_API_KEY=${N8N_API_KEY}
      - HOST_AGENT_BEARER_TOKEN=${HOST_AGENT_BEARER_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - supabase

networks:
  supabase:
    name: supabase_default
    external: true