services:
  ai-dev-server:
    image: registry.correlion.ai/ai-dev-server:latest
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - supabase

networks:
  supabase:
    name: supabase_default
    external: true