services:
    registry:
      image: registry:2
      container_name: registry
      restart: unless-stopped
      ports:
        - "127.0.0.1:5000:5000"
      volumes:
        - /srv/docker-registry/data:/var/lib/registry
        - /srv/docker-registry/auth:/auth
      environment:
        - REGISTRY_AUTH=htpasswd
        - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      networks:
        - supabase

  networks:
    supabase:
      external: true