services:
  n8n-workflows:
    image: registry.correlion.ai/n8n-workflows:latest
    container_name: n8n-workflows
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    networks:
      - supabase

networks:
  supabase:
    name: supabase_default
    external: true