name: Deploy N8N Workflows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64 -t registry.correlion.ai/n8n-workflows:latest --push .
        
    - name: Deploy to VPS
      run: |
        /home/david/vps/github-runner/deploy-n8n-workflows.sh